### PR TITLE
Add lightweight permission checking parameters

### PR DESCRIPTION
**Pull request by davedx**

### CODE REVIEW

**Comment by davedx** [comment]
:+1: or :-1: ?

**Comment by davedx** [comment]
Hey there, I've published a smart package called "flextags" to atmosphere that has our changes for now, as we need it to be in atmosphere for mrt to work properly with our project. If you get the chance to look at this PR and get it merged let me know and I'll take down the flextags project and go back to using meteor-tags. :)

**Comment by apendua** [comment]
@davedx Sorry for not having replied for so long. I am planning to reimplement the tags UI by using several other usefull packages like `bootstrap-tagsinput` and `typeahead` and that's why I am not merging this PR. If you're interested in future cooperation on this project, you're very wellcome.

**Comment by dandv** [comment]
[bootstrap-tagsinput looks good, but hasn't been maintained in 6 months.](https://github.com/TimSchlechter/bootstrap-tagsinput/issues/123) I would consider Select2 instead.

**Comment by apendua** [comment]
@dandv Thank you for this suggestion, I will take a look.

**Comment by apendua** [comment]
Wow, their demo site looks incredible! This is definitely worth considering...

**Comment by dandv** [comment]
And Select2 also [integrates with Bootstrap 2 and 3](https://github.com/ivaynberg/select2/pull/2281).

**Pull request closed without merging**
